"""Respond node: the ONE bounded autonomous action Aegis takes.

Deterministic, no LLM involved — this is a safety-critical decision and
must be reliable and testable. Auto-blocks a confirmed-malicious IP (High
severity + threat-intel reputation "malicious" + risk score above
threshold) to a local blocklist file. Everything else stays a human-facing
recommendation generated by the Report node.

See PROJECT_DOCUMENTATION.md §5.5 and §7a.
"""

from __future__ import annotations

import json
from datetime import datetime, timezone
from pathlib import Path

from ..config import get_thresholds
from ..state import AgentState

BLOCKLIST_PATH = Path("blocklist.json")


def _load_blocklist() -> list[dict]:
    if BLOCKLIST_PATH.exists():
        with open(BLOCKLIST_PATH, encoding="utf-8") as f:
            return json.load(f)
    return []


def _save_blocklist(entries: list[dict]) -> None:
    with open(BLOCKLIST_PATH, "w", encoding="utf-8") as f:
        json.dump(entries, f, indent=2)


def respond_node(state: AgentState) -> AgentState:
    findings = state.get("findings", [])
    thresholds = get_thresholds()

    blocklist = _load_blocklist()
    already_blocked = {e["ip"] for e in blocklist}
    actions_taken = []

    for f in findings:
        ip = f.get("ip")
        if not ip or ip in already_blocked:
            continue
        threat_intel = f.get("threat_intel") or {}
        is_confirmed_malicious = (
            threat_intel.get("reputation") == "malicious"
            and float(threat_intel.get("risk_score", 0.0)) >= thresholds.auto_block_min_risk_score
        )
        if is_confirmed_malicious and f.get("severity") == "High":
            entry = {
                "ip": ip,
                "reason": f.get("pattern") or f.get("anomaly"),
                "confidence": f.get("confidence"),
                "blocked_at": datetime.now(timezone.utc).isoformat(),
            }
            blocklist.append(entry)
            actions_taken.append(entry)
            already_blocked.add(ip)

    if actions_taken:
        _save_blocklist(blocklist)

    trail = list(state.get("reasoning_trail", []))
    trail.append(
        f"Respond: auto-blocked {len(actions_taken)} IP(s)."
        if actions_taken
        else "Respond: no findings met the auto-block bar; nothing auto-executed."
    )

    return {**state, "autonomous_actions_taken": actions_taken, "reasoning_trail": trail}
